// SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
//
// SPDX-License-Identifier: MIT

package main

import (
	"os"
	"path/filepath"
	"testing"

	"projectfile.org/projectfile/ci/internal/ci"
	"projectfile.org/projectfile/ci/internal/render"
)

// testGoalReady is the single goal node fixture below (goconst).
const testGoalReady = "ready"

// TestWorkflowFilesUndeclaredTargetRendersNothing pins §3.7: a target absent from
// org.projectfile.ci.targets renders no files and errors on neither Load nor Parse.
func TestWorkflowFilesUndeclaredTargetRendersNothing(t *testing.T) {
	dir := t.TempDir()
	st := &ci.Subtree{
		GoalsExplicit: true,
		Goals:         []string{testGoalReady},
		Nodes:         map[string]ci.Node{testGoalReady: {Name: testGoalReady, Goal: true}},
		Targets:       []string{ci.LoweringForgejo}, // gha deliberately absent
	}
	target := render.Target{Key: ci.LoweringGHA, OutDir: dir, Ext: ".yaml"}
	files, gotDir, err := workflowFiles(st, target, "", "")
	if err != nil {
		t.Fatalf("workflowFiles: %v", err)
	}
	if len(files) != 0 {
		t.Fatalf("workflowFiles: got %d files, want none", len(files))
	}
	if gotDir != dir {
		t.Fatalf("workflowFiles: dir got %q, want %q", gotDir, dir)
	}
}

// TestWriteWorkflowDirRemovesOrphan pins §3.7's "generate removes its orphans": a
// stale generated file whose target dropped out of ci.targets is deleted, a
// hand-written file of the same extension is left alone.
func TestWriteWorkflowDirRemovesOrphan(t *testing.T) {
	dir := t.TempDir()
	stale := filepath.Join(dir, "published.yaml")
	if err := os.WriteFile(stale, []byte("# Generated by pf-ci\nname: published\n"), 0o644); err != nil {
		t.Fatalf("seed stale file: %v", err)
	}
	handWritten := filepath.Join(dir, "manual.yaml")
	if err := os.WriteFile(handWritten, []byte("name: manual\n"), 0o644); err != nil {
		t.Fatalf("seed hand-written file: %v", err)
	}
	if err := writeWorkflowDir(dir, ".yaml", map[string][]byte{}); err != nil {
		t.Fatalf("writeWorkflowDir: %v", err)
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Fatalf("writeWorkflowDir: orphan %s still present (err=%v)", stale, err)
	}
	if _, err := os.Stat(handWritten); err != nil {
		t.Fatalf("writeWorkflowDir: hand-written file removed: %v", err)
	}
}

// TestCheckFreshDirReportsOrphan pins the -check half: an orphan fails loud instead
// of silently surviving the freshness gate.
func TestCheckFreshDirReportsOrphan(t *testing.T) {
	dir := t.TempDir()
	stale := filepath.Join(dir, "published.yaml")
	if err := os.WriteFile(stale, []byte("# Generated by pf-ci\nname: published\n"), 0o644); err != nil {
		t.Fatalf("seed stale file: %v", err)
	}
	if err := checkFreshDir(dir, ".yaml", map[string][]byte{}); err == nil {
		t.Fatalf("checkFreshDir: got nil error, want an orphan failure for %s", stale)
	}
}
