// SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
//
// SPDX-License-Identifier: MIT

package main

import (
	"bytes"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"projectfile.org/projectfile/ci/internal/ci"
	"projectfile.org/projectfile/ci/internal/render"
)

// testGoalReady is the single goal node fixture below (goconst).
const testGoalReady = "ready"

// TestWorkflowFilesUndeclaredTargetRendersNothing pins §3.7: a target absent from
// org.projectfile.ci.targets renders no files and errors on neither Load nor Parse.
func TestWorkflowFilesUndeclaredTargetRendersNothing(t *testing.T) {
	dir := t.TempDir()
	st := &ci.Subtree{
		GoalsExplicit: true,
		Goals:         []string{testGoalReady},
		Nodes:         map[string]ci.Node{testGoalReady: {Name: testGoalReady, Goal: true}},
		Targets:       []string{ci.LoweringForgejo}, // gha deliberately absent
	}
	target := render.Target{Key: ci.LoweringGHA, OutDir: dir, Ext: ".yaml"}
	files, gotDir, err := workflowFiles(st, target, "", "")
	if err != nil {
		t.Fatalf("workflowFiles: %v", err)
	}
	if len(files) != 0 {
		t.Fatalf("workflowFiles: got %d files, want none", len(files))
	}
	if gotDir != dir {
		t.Fatalf("workflowFiles: dir got %q, want %q", gotDir, dir)
	}
}

// TestWriteWorkflowDirRemovesOrphan pins §3.7's "generate removes its orphans": a
// stale generated file whose target dropped out of ci.targets is deleted, a
// hand-written file of the same extension is left alone.
func TestWriteWorkflowDirRemovesOrphan(t *testing.T) {
	dir := t.TempDir()
	stale := filepath.Join(dir, "published.yaml")
	if err := os.WriteFile(stale, []byte("# Generated by pf-ci\nname: published\n"), 0o644); err != nil {
		t.Fatalf("seed stale file: %v", err)
	}
	handWritten := filepath.Join(dir, "manual.yaml")
	if err := os.WriteFile(handWritten, []byte("name: manual\n"), 0o644); err != nil {
		t.Fatalf("seed hand-written file: %v", err)
	}
	if err := writeWorkflowDir(dir, ".yaml", map[string][]byte{}, false, true, io.Discard); err != nil {
		t.Fatalf("writeWorkflowDir: %v", err)
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Fatalf("writeWorkflowDir: orphan %s still present (err=%v)", stale, err)
	}
	if _, err := os.Stat(handWritten); err != nil {
		t.Fatalf("writeWorkflowDir: hand-written file removed: %v", err)
	}
}

// TestCheckFreshDirReportsOrphan pins the -check half: an orphan fails loud instead
// of silently surviving the freshness gate.
func TestCheckFreshDirReportsOrphan(t *testing.T) {
	dir := t.TempDir()
	stale := filepath.Join(dir, "published.yaml")
	if err := os.WriteFile(stale, []byte("# Generated by pf-ci\nname: published\n"), 0o644); err != nil {
		t.Fatalf("seed stale file: %v", err)
	}
	if err := checkFreshDir(dir, ".yaml", map[string][]byte{}); err == nil {
		t.Fatalf("checkFreshDir: got nil error, want an orphan failure for %s", stale)
	}
}

// TestSubcommandHelp pins that every help spelling prints that subcommand’s help to stdout and exits 0.
func TestSubcommandHelp(t *testing.T) {
	const help, gen, res = "--help", "generate", "resolve"
	for _, tc := range []struct {
		sub  string
		args []string
	}{
		{res, []string{res, help}},
		{res, []string{res, "-h"}},
		{gen, []string{gen, "-target", "gha", "-check", help}},
		{gen, []string{"help", gen}},
		{gen, []string{help, gen}},
	} {
		var stdout, stderr bytes.Buffer
		if code := run(tc.args, nil, &stdout, &stderr); code != 0 {
			t.Fatalf("%v: exit %d, want 0 (stderr=%q)", tc.args, code, stderr.String())
		}
		if !strings.Contains(stdout.String(), "pf-ci "+tc.sub+" ") {
			t.Fatalf("%v: stdout %q lacks %s usage", tc.args, stdout.String(), tc.sub)
		}
		if strings.Contains(stdout.String()+stderr.String(), "help requested") {
			t.Fatalf("%v: leaked flag.ErrHelp text", tc.args)
		}
	}
}

// TestUnknownFlagIsUsageError pins that a bad flag exits 2 with the subcommand’s help on stderr.
func TestUnknownFlagIsUsageError(t *testing.T) {
	var stdout, stderr bytes.Buffer
	if code := run([]string{"resolve", "-nope"}, nil, &stdout, &stderr); code != 2 {
		t.Fatalf("exit %d, want 2", code)
	}
	if !strings.Contains(stderr.String(), "pf-ci resolve ") {
		t.Fatalf("stderr %q lacks resolve usage", stderr.String())
	}
}

// TestQuietFlag pins -q and -quiet on every subcommand.
func TestQuietFlag(t *testing.T) {
	for name := range commands {
		for _, flagName := range []string{"-q", "-quiet"} {
			fs, o, _ := newFlagSet(name)
			if err := fs.Parse([]string{flagName}); err != nil || !o.quiet {
				t.Fatalf("%s %s: quiet=%v err=%v, want quiet", name, flagName, o.quiet, err)
			}
		}
	}
}

// TestDashProjectfileReadsStdin pins `-pf -`: the document comes from stdin and its staging file is gone after the run.
func TestDashProjectfileReadsStdin(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	for _, tc := range []struct {
		doc  string
		code int
	}{{"name: demo\n", 0}, {"name: [unclosed\n", 1}} {
		var stdout, stderr bytes.Buffer
		if code := run([]string{"resolve", "-pf", "-"}, strings.NewReader(tc.doc), &stdout, &stderr); code != tc.code {
			t.Fatalf("doc %q: exit %d, want %d (stderr=%q)", tc.doc, code, tc.code, stderr.String())
		}
		if left, _ := os.ReadDir(dir); len(left) != 0 {
			t.Fatalf("doc %q: staging file left behind: %v", tc.doc, left)
		}
	}
}

// TestDashOutputRefused pins `-o -`: a usage error, and no directory named - is ever created.
func TestDashOutputRefused(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	var stdout, stderr bytes.Buffer
	if code := run([]string{"generate", "-target", "gha", "-o", "-"}, nil, &stdout, &stderr); code != 2 {
		t.Fatalf("exit %d, want 2 (stderr=%q)", code, stderr.String())
	}
	if err := writeWorkflow(filepath.Join("-", "build.yaml"), []byte("x")); err == nil {
		t.Fatal("writeWorkflow: got nil error for a - path element")
	}
	if _, err := os.Stat(filepath.Join(dir, "-")); !os.IsNotExist(err) {
		t.Fatalf("a directory named - exists (err=%v)", err)
	}
}

// TestWriteWorkflowDirDryRunAndNoForce pins -dry-run (plan on stdout, nothing touched) and -force=false (orphan kept, run fails naming -force).
func TestWriteWorkflowDirDryRunAndNoForce(t *testing.T) {
	dir := t.TempDir()
	stale := filepath.Join(dir, "published.yaml")
	if err := os.WriteFile(stale, []byte("# Generated by pf-ci\nname: published\n"), 0o644); err != nil {
		t.Fatalf("seed stale file: %v", err)
	}
	fresh := filepath.Join(dir, "build.yaml")
	files := map[string][]byte{fresh: []byte("name: build\n")}
	var plan bytes.Buffer
	if err := writeWorkflowDir(dir, ".yaml", files, true, true, &plan); err != nil {
		t.Fatalf("dry run: %v", err)
	}
	if want := "write " + fresh + "\nremove " + stale + "\n"; plan.String() != want {
		t.Fatalf("dry run plan %q, want %q", plan.String(), want)
	}
	if _, err := os.Stat(fresh); !os.IsNotExist(err) {
		t.Fatalf("dry run wrote %s (err=%v)", fresh, err)
	}
	err := writeWorkflowDir(dir, ".yaml", files, false, false, io.Discard)
	if err == nil || !strings.Contains(err.Error(), "-force") {
		t.Fatalf("no-force run: err=%v, want one naming -force", err)
	}
	if _, err := os.Stat(stale); err != nil {
		t.Fatalf("no-force run removed the orphan: %v", err)
	}
}
